name: CI-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: unit testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v2

    - name: Set test directory
      run : |
        echo "::set-env name=TESTS::tests/"

    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools -y
        pip3 install --upgrade pip
        pip3 install -e .
        pip3 install -r requirements.txt

    - name: Set a run prefix
      run : |
        echo "::set-env name=RUN::python3 -m"

    - name: Test with pytest
      run: |
        $RUN pytest $TESTS


  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
          python36-ubuntu1804,
          python38-ubuntu2004,
          python37-macOS
        ]
        include:
        - name: python36-ubuntu1804
          python-version: 3.6
          os: ubuntu-18.04

        - name: python38-ubuntu2004
          python-version: 3.8
          os: ubuntu-20.04

        - name: python37-macOs
          python-version: 3.7
          os: macos-latest

    steps:
      - name: Install dependencies
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get install python3-setuptools -y
          pip3 install --upgrade pip
          pip3 install -e
          pip3 install -r requirements.txt
      
      - name: Install dependencies (MacOsX)
        if: matrix.os == 'macos-latest'
        run: |
          curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O -| python
          pip install --upgrade pip
          pip install -e
          pip install -r requirements.txt
